[package]
name = "worst_sudoku_cli"
version = "0.1.0"
edition = "2021"

[build]
rustc-wrapper = "sccache"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Zlinker-features=-mold"]

[dependencies]
rand = "0.8.5"